os.system('cls')
        print(logo)
        print('Do jaké kategorie mám recept zařadit?')
        print()
        print()
        print('1: Bezmasá jídla')
        print('2: Maso')
        print('3: Ryby')
        print('4: Polévky')
        print('5: Saláty')
        print('6: Sladká jídla')
        print('7: Přílohy')
        print('8: Omáčky')
        print('9: Předkrmy')
        print('10: Moučníky')
        input()
